// Units format: one unit = { id, title, subtitle, sections: [{ name, words }] }
// words: [{ hu, en: [alternatives] }]. HU is shown, you type the EN.
// Checker is case-insensitive, ignores extra spaces and a leading "to ".
// To add a unit: copy the template at the bottom. Nothing else changes.
const UNITS = [
  {
    id: "u5",
    title: "Unit 5 — The World of Work",
    subtitle: "Wordlist 5 · 6 sections, ~190 phrases",
    sections: [
      {
        name: "Summer & part-time jobs",
        words: [
      { hu: "teljes / részmunkaidős állás", en: ["full-time job", "part-time job", "full time job", "part time job"] },
      { hu: "alkalmi munka", en: ["casual work"] },
      { hu: "(diák)munka közvetítő", en: ["(student) job centre", "student job centre", "job centre"] },
      { hu: "munkavállalási engedélyt szerez", en: ["get a work permit", "get work permit"] },
      { hu: "nyári munkát keres", en: ["look for a summer job"] },
      { hu: "nyári munkát vállal / végez", en: ["take a summer job", "do a summer job"] },
      { hu: "plusz pénzt keres", en: ["earn extra money"] },
      { hu: "pénzt félretesz vmire", en: ["save money for sth", "save money for something"] },
      { hu: "hasznosan tölti a nyarat", en: ["spend the summer in a meaningful way"] },
      { hu: "tapasztalatot szerez", en: ["gain some experience", "gain experience"] },
      { hu: "kapcsolatokat épít", en: ["make contacts"] },
      { hu: "fegyelmet tanul", en: ["learn discipline"] },
      { hu: "új készségekre tesz szert", en: ["learn new skills"] },
      { hu: "hasznát látja vminek", en: ["benefit from sth", "benefit from something"] },
      { hu: "irodában dolgozik / irodai asszisztens", en: ["work in an office", "be an office assistant"] },
      { hu: "recepciósként / hostessként dolgozik", en: ["work as a receptionist", "work as a hostess"] },
      { hu: "gyakornokként dolgozik", en: ["work as an apprentice"] },
      { hu: "gyorsétteremben dolgozik", en: ["work in a fast food restaurant", "work in a fast-food restaurant"] },
      { hu: "a pultnál áll", en: ["stand at the counter"] },
      { hu: "árufeltöltőként dolgozik", en: ["stock shelves"] },
      { hu: "(futó)szalag mellett dolgozik", en: ["work at a conveyor belt"] },
      { hu: "szórólapozik", en: ["hand out leaflets"] },
      { hu: "szórólapot terjeszt", en: ["deliver leaflets"] },
      { hu: "újságot házhoz visz", en: ["do a paper round"] },
      { hu: "forgalmat számlál", en: ["monitor traffic flow"] },
      { hu: "segít a családi vállalkozásban", en: ["work in the family business"] },
      { hu: "jogosítvánnyal rendelkezik", en: ["have a driving licence", "have a driving license"] },
      { hu: "ideges / izgul", en: ["have butterflies in one's stomach", "have butterflies in ones stomach"] }
      ]
      },
      {
        name: "Job interview",
        words: [
      { hu: "álláskereső", en: ["job seeker", "jobseeker"] },
      { hu: "állásra jelentkező", en: ["job applicant"] },
      { hu: "megpályáz egy állást", en: ["apply for a job"] },
      { hu: "jelölt", en: ["candidate"] },
      { hu: "kitölti a jelentkezési lapot", en: ["fill in an application form"] },
      { hu: "beadja az önéletrajzát", en: ["hand in a CV"] },
      { hu: "CV (szakmai önéletrajz)", en: ["curriculum vitae", "cv"] },
      { hu: "motivációs levelet ír", en: ["write a cover letter"] },
      { hu: "ajánlásokat szerez", en: ["get references"] },
      { hu: "állásinterjúra megy", en: ["go to a job interview"] },
      { hu: "időben érkezik", en: ["arrive in time"] },
      { hu: "elegáns", en: ["look smart"] },
      { hu: "jó benyomást kelt", en: ["make a good impression"] },
      { hu: "alkalmas vmire", en: ["be suitable for"] },
      { hu: "megfelel a követelményeknek", en: ["meet the requirements"] },
      { hu: "végzettségéről / munkatapasztalatairól / készségeiről beszél", en: ["talk about one's qualifications / job experience / skills", "talk about ones qualifications / job experience / skills", "talk about one's qualifications", "talk about job experience", "talk about skills"] },
      { hu: "személyes tulajdonságok", en: ["personal qualities"] },
      { hu: "megfelelő végzettsége van", en: ["have good qualifications"] },
      { hu: "nyelveket beszél", en: ["speak languages"] }
      ]
      },
      {
        name: "Higher education",
        words: [
      { hu: "leteszi az érettségit", en: ["pass the school-leaving exam", "pass the school leaving exam"] },
      { hu: "megbeszéli a pályaválasztási lehetőségeket a szülőkkel", en: ["discuss career options with parents"] },
      { hu: "pályaválasztási tanácsadóhoz fordul", en: ["talk to a careers adviser", "talk to a careers advisor"] },
      { hu: "pályát választ", en: ["make a career decision"] },
      { hu: "egyetemre / főiskolára jelentkezik / jár", en: ["apply for university", "go to university", "attend university", "apply for college", "go to college", "attend college"] },
      { hu: "államilag finanszírozott képzés", en: ["state-funded training", "state funded training"] },
      { hu: "költségtérítéses képzés", en: ["fee-paying training", "fee paying training"] },
      { hu: "végez vhol", en: ["graduate from"] },
      { hu: "diplomát szerez vmiből", en: ["get a degree in sth", "get a degree in something"] },
      { hu: "Közgazdaságtudományi Egyetem", en: ["university of economics"] },
      { hu: "Műszaki Egyetem", en: ["university of technology"] },
      { hu: "Orvostudományi Egyetem", en: ["university of medicine"] },
      { hu: "Jogtudományi Kar", en: ["faculty of law"] },
      { hu: "Bölcsészettudományi Kar", en: ["faculty of arts"] },
      { hu: "Természettudományi Kar", en: ["faculty of sciences"] },
      { hu: "Agrártudományi Egyetem", en: ["university of agriculture"] },
      { hu: "Képzőművészeti Egyetem", en: ["academy of fine arts"] },
      { hu: "Színház és Filmművészeti Egyetem", en: ["academy of film and theatrical arts"] },
      { hu: "Zeneművészeti Akadémia", en: ["academy of music"] },
      { hu: "Kereskedelmi és Vendéglátóipari Főiskola", en: ["college of trade and catering"] },
      { hu: "Külkereskedelmi Főiskola", en: ["college of foreign trade"] },
      { hu: "Pénzügyi és Számviteli Főiskola", en: ["college of finance and accounting"] },
      { hu: "Tanárképző Főiskola", en: ["teacher training college"] },
      { hu: "előadás / szeminárium (gyakorlati foglalkozás)", en: ["lecture", "seminar", "lecture / seminar"] },
      { hu: "vizsgaidőszak", en: ["exam period"] },
      { hu: "elsőéves (gólya) / másodéves / végzős", en: ["freshman", "sophomore", "senior"] },
      { hu: "főiskolai végzettségű", en: ["bachelor of arts (ba)", "bachelor of sciences (bsc)", "bachelor of arts", "bachelor of sciences", "ba", "bsc"] },
      { hu: "egyetemi végzettségű", en: ["master of arts (ma)", "master of sciences (msc)", "master of arts", "master of sciences", "ma", "msc"] },
      { hu: "szállás", en: ["accommodation"] },
      { hu: "kollégium", en: ["student hostel", "hostel"] },
      { hu: "megosztja a szobáját vkivel", en: ["share one's room with sy", "share ones room with sy", "share one's room with somebody", "share ones room with somebody"] },
      { hu: "napi rendszerességgel tanul", en: ["learn on a daily basis"] },
      { hu: "megél", en: ["make ends meet"] },
      { hu: "ösztöndíjat kap", en: ["get a scholarship"] },
      { hu: "diákhitelért folyamodik", en: ["apply for a student loan"] },
      { hu: "visszafizeti a diákhitelt", en: ["pay the student loan back", "pay back the student loan"] },
      { hu: "munkaerőpiac", en: ["labour market", "labor market"] },
      { hu: "nagy kereslet vmire", en: ["great demand for sth", "great demand for something"] }
      ]
      },
      {
        name: "Jobs",
        words: [
      { hu: "hivatás, szakma", en: ["profession"] },
      { hu: "munkaadó", en: ["employer"] },
      { hu: "munkavállaló, alkalmazott", en: ["employee"] },
      { hu: "szellemi / fizikai munka", en: ["white collar job", "blue collar job", "white-collar job", "blue-collar job", "mental work", "physical work"] },
      { hu: "kemény fizikai munka", en: ["hard physical work"] },
      { hu: "szellemi munka", en: ["mental work", "intellectual work", "mental / intellectual work"] },
      { hu: "adminisztratív munka", en: ["administrative work"] },
      { hu: "szakképzett / szakképzetlen munkás", en: ["skilled worker", "unskilled worker", "(un)skilled worker"] },
      { hu: "szabadúszó", en: ["be a freelancer", "freelancer"] },
      { hu: "egyéni vállalkozó", en: ["be self-employed", "self-employed"] },
      { hu: "(multinacionális) cégnél dolgozik", en: ["work for a (multinational) company", "work for a multinational company", "work for a company"] },
      { hu: "üzletember / üzletasszony", en: ["businessman", "businesswoman", "businessman / -woman"] },
      { hu: "közgazdász", en: ["economist"] },
      { hu: "mérnök", en: ["engineer"] },
      { hu: "ügyvéd", en: ["lawyer"] },
      { hu: "programozó", en: ["computer programmer", "programmer"] },
      { hu: "építész", en: ["architect"] },
      { hu: "fogorvos", en: ["dentist"] },
      { hu: "ápolónő", en: ["nurse"] },
      { hu: "könyvelő", en: ["accountant"] },
      { hu: "politikus", en: ["politician"] },
      { hu: "pap", en: ["priest"] },
      { hu: "szociális munkás", en: ["social worker"] },
      { hu: "újságíró", en: ["journalist"] },
      { hu: "tévébemondó", en: ["tv presenter"] },
      { hu: "színész / színésznő", en: ["actor", "actress", "actor / actress"] },
      { hu: "sportoló", en: ["sportsman", "sportswoman", "sportsman / -woman"] },
      { hu: "edző", en: ["coach", "trainer", "coach / trainer"] },
      { hu: "rendőr", en: ["policeman", "policewoman", "policeman / -woman"] },
      { hu: "katona", en: ["soldier"] },
      { hu: "tűzoltó", en: ["fireman"] },
      { hu: "ügynök (kereskedelmi)", en: ["salesman", "saleswoman", "salesman / -woman"] },
      { hu: "busz- / teherautósofőr", en: ["bus driver", "lorry driver", "bus / lorry driver"] },
      { hu: "boltos", en: ["shopkeeper"] },
      { hu: "szakács", en: ["cook"] },
      { hu: "pincér / pincérnő", en: ["waiter", "waitress", "waiter / waitress"] },
      { hu: "kőműves", en: ["bricklayer"] },
      { hu: "asztalos", en: ["carpenter"] },
      { hu: "vízvezetékszerelő", en: ["plumber"] },
      { hu: "villanyszerelő", en: ["electrician"] }
      ]
      },
      {
        name: "Pay, conditions & leaving",
        words: [
      { hu: "egyenruhát visel", en: ["wear a uniform"] },
      { hu: "magas beosztásban van", en: ["have a high position"] },
      { hu: "jó fizetés / bér", en: ["good salary", "good wage", "good salary / wage"] },
      { hu: "jól / rosszul fizetett", en: ["well-paid", "badly-paid", "well paid", "badly paid", "be well-paid", "be badly-paid", "be well paid", "be badly paid"] },
      { hu: "fizetésemelést kap", en: ["get a pay rise"] },
      { hu: "jutalmat kap", en: ["get a bonus"] },
      { hu: "előléptetik", en: ["get promoted"] },
      { hu: "táppénzen van", en: ["be on sick leave"] },
      { hu: "GYES-en van", en: ["be on maternity leave"] },
      { hu: "kivesz egy szabadnapot", en: ["take a day off"] },
      { hu: "céges autó / mobiltelefon", en: ["company car", "cell phone", "company cell phone", "company car / cell phone"] },
      { hu: "kellemes légkör / munkakörülmények", en: ["pleasant atmosphere", "working conditions", "pleasant working conditions"] },
      { hu: "munkatárs / csapattárs", en: ["workmate", "teammate", "workmate / teammate"] },
      { hu: "munkával való elégedettség", en: ["job satisfaction"] },
      { hu: "unja a munkáját", en: ["be bored by one's work", "be bored by ones work"] },
      { hu: "megbecsülés / presztízs", en: ["esteem", "prestige", "esteem / prestige"] },
      { hu: "eredményes", en: ["rewarding"] },
      { hu: "kihívást jelentő", en: ["challenging"] },
      { hu: "motiváló", en: ["motivating"] },
      { hu: "fárasztó", en: ["tiring"] },
      { hu: "kimerítő", en: ["exhausting"] },
      { hu: "megerőltető", en: ["demanding"] },
      { hu: "biztonságos", en: ["secure"] },
      { hu: "egyhangú", en: ["monotonous"] },
      { hu: "unalmas", en: ["dull"] },
      { hu: "nyugdíjba megy", en: ["retire"] },
      { hu: "elveszíti a munkáját", en: ["lose one's job", "lose ones job"] },
      { hu: "elbocsátják", en: ["get sacked", "get fired", "get sacked / fired"] },
      { hu: "beadja a felmondását", en: ["hand in one's notice", "hand in ones notice"] },
      { hu: "munkanélküli", en: ["be unemployed", "unemployed"] },
      { hu: "munkanélküli segélyen él", en: ["be on the dole"] },
      { hu: "üres állások", en: ["job vacancies", "vacancies"] }
      ]
      },
      {
        name: "At work & competencies",
        words: [
      { hu: "munkát talál / szerez", en: ["find a job", "get a job", "find / get a job"] },
      { hu: "aláírja a munkaszerződést", en: ["sign the work contract", "sign a work contract"] },
      { hu: "dolgozni kezd", en: ["start work"] },
      { hu: "ingázik", en: ["commute"] },
      { hu: "reggel 8-tól este 5-ig tartó munka", en: ["an 8 to 5 job", "8 to 5 job"] },
      { hu: "fix / rugalmas munkaidőben dolgozik", en: ["work fixed hours", "work flexitime", "flexitime"] },
      { hu: "több műszakban dolgozik", en: ["work shifts"] },
      { hu: "nappali / éjszakai műszakban dolgozik", en: ["work the day shift", "work the night shift", "work the day / night shift"] },
      { hu: "túlórázik", en: ["work overtime", "do overtime"] },
      { hu: "zárt térben / szabadban dolgozik", en: ["work indoors", "work outdoors", "work indoors / outdoors"] },
      { hu: "öltözködési szabályok", en: ["dress code"] },
      { hu: "önállóan dolgozik", en: ["work independently"] },
      { hu: "képes a csapatmunkára", en: ["be capable of teamwork"] },
      { hu: "beosztja az idejét", en: ["organise one's time", "organize one's time", "organise ones time", "organize ones time"] },
      { hu: "fontossági sorrendet állít fel", en: ["prioritize", "prioritise"] },
      { hu: "döntést hoz", en: ["make a decision"] },
      { hu: "problémákat old meg", en: ["solve problems"] },
      { hu: "hatékonyan kommunikál", en: ["communicate effectively"] },
      { hu: "felelősséget vállal vmiért", en: ["take responsibility for"] },
      { hu: "használja a technológiai eszközöket", en: ["use technology"] },
      { hu: "követi az utasításokat", en: ["follow guidelines"] },
      { hu: "van alkalmazkodó készsége", en: ["be able to adapt"] },
      { hu: "tartja magát a szabályokhoz", en: ["keep to rules"] },
      { hu: "betartja a határidőket", en: ["keep deadlines"] },
      { hu: "önképzés", en: ["self-development"] },
      { hu: "önreklám", en: ["self-promotion"] },
      { hu: "kapacitás", en: ["capacity"] },
      { hu: "motiváció", en: ["motivation"] },
      { hu: "optimizmus", en: ["optimism"] },
      { hu: "vélemény", en: ["opinion"] },
      { hu: "visszacsatolás", en: ["feedback"] },
      { hu: "hatékony időbeosztás", en: ["time management"] },
      { hu: "rugalmasság", en: ["flexibility"] }
        ]
      }
    ]
  }
];

// Template for the next photo wordlist — copy, paste above, fill in:
// {
//   id: "u6",
//   title: "Unit 6 — <topic>",
///   subtitle: "Wordlist 6 · …",
///   sections: [
//     { name: "<section>", words: [{ hu: "…", en: ["…"] }] },
//   ]
// },
